apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 105Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /mnt/okd-infra-registry
    server: host-1.example.net
  persistentVolumeReclaimPolicy: Retain
