---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: prometheus-og
  namespace: my-monitoring
spec:
  targetNamespaces:
  - my-monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-sub
  namespace: my-monitoring 
spec:
  channel: beta
  name: prometheus
  installPlanApproval: Automatic
  source: community-operators 
  sourceNamespace: openshift-marketplace
