---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: prometheus-og
  namespace: wumii-monitoring
spec:
  targetNamespaces:
  - wumii-monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-sub
  namespace: wumii-monitoring 
spec:
  channel: beta
  name: prometheus
  installPlanApproval: Automatic
  source: community-operators 
  sourceNamespace: openshift-marketplace
