---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: my-monitoring
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: my-monitoring
spec:
  selector:
    alertmanager: alertmanager
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
