---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-sub
  namespace: my-monitoring
spec:
  channel: alpha
  name: grafana-operator
  source: community-operators
  installPlanApproval: Automatic
  sourceNamespace: openshift-marketplace
