apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: wumii-monitoring
spec:
  ingress:
    enabled: true
  configMaps:
      - ldap-config
      - wumii-ca
  config:
    auth.ldap:
      enabled: true
      config_file: /etc/grafana-configmaps/ldap-config/ldap.toml
    users:
      auto_assign_org_role: Admin
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
