apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
  namespace: wumii-monitoring
data:
  ldap.toml: |
    [[servers]]
    host = "ipa.example.net"
    port = 636
    use_ssl = true
    start_tls = false
    ssl_skip_verify = true
    root_ca_cert = "/etc/grafana-configmaps/wumii-ca/wumii-internal.crt"
    search_filter = "(uid=%s)"
    search_base_dns = ["cn=users,cn=accounts,dc=wumii,dc=net"]
    [servers.attributes]
    name = "givenName"
    surname = "sn"
    username = "cn"
